RssFeed.Web/Controllers/PersonalFeedsController.cs
namespace RssFeed.Web.Controllers
{
    using System.Linq;
    using System.Transactions;
    using System.Web.Mvc;

    using AutoMapper;
    using AutoMapper.QueryableExtensions;

    using RssFeed.Services.Feeds;
    using RssFeed.Services.PersonalCategories;
    using RssFeed.Services.UsersService;
    using RssFeed.Web.Models;

    using RssFeed.Data.Models;
    using RssFeed.Data.Repositories.Contracts;

    public class PersonalFeedsController : BaseAuthorizedController
    {
        private readonly IDeletableEntityRepository<Feed> feedsRepository;
        private readonly IDeletableEntityRepository<PersonalFeed> personalFeedsRepository;
        private readonly IFeedsService feedsService;
        private readonly IPersonalCategoriesService personalCategoriesService;

        public PersonalFeedsController(
            IUsersService<User> usersService,
            IDeletableEntityRepository<Feed> feedsRepository,
            IDeletableEntityRepository<PersonalFeed> personalFeedsRepository,
            IFeedsService feedsService,
            IPersonalCategoriesService personalCategoriesService) 
            : base(usersService)
        {
            this.feedsRepository = feedsRepository;
            this.personalFeedsRepository = personalFeedsRepository;
            this.feedsService = feedsService;
            this.personalCategoriesService = personalCategoriesService;
        }

        // GET: PersonalFeeds
        public ActionResult Index()
        {
            var personalFeedViewModels = 
                this.personalFeedsRepository
                .All()
                .ProjectTo<PersonalFeedViewModel>()
                .ToList();

            return this.View(personalFeedViewModels);
        }

        // GET: PersonalFeeds/Details/5
        public ActionResult Details(long? id)
        {
            PersonalFeed personalFeed = this.personalFeedsRepository.GetById(id);

            if (personalFeed == null)
            {
                return this.HttpNotFound();
            }

            var personalFeedViewModel = Mapper.Map<PersonalFeedViewModel>(personalFeed);

            return this.View(personalFeedViewModel);
        }

        // GET: PersonalFeeds/Create
        public ActionResult Create()
        {
            var categories = this.personalCategoriesService.GetByUser(this.UserProfile.Id);
            this.ViewBag.CategoryId = new SelectList(categories, "Id", "Name");
            //this.ViewBag.FeedId = new SelectList(this.db.Feeds, "Id", "Url");
            return this.View();
        }

        // POST: PersonalFeeds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PersonalFeedInputModel personalFeedInputModel)
        {
            if (this.ModelState.IsValid)
            {
                if (!this.feedsService.ExistsByUrl(personalFeedInputModel.Url))
                {
                    this.feedsRepository.Add(new Feed() {Url = personalFeedInputModel.Url});    
                }

                var feed = this.feedsService.GetByUrl(personalFeedInputModel.Url);

                var personalFeed = Mapper.Map<PersonalFeed>(personalFeedInputModel);
                personalFeed.FeedId = feed.Id;

                this.personalFeedsRepository.Add(personalFeed);
                this.feedsRepository.SaveChanges();

                //this.db.PersonalFeeds.Add(personalFeed);
                //this.db.SaveChanges();
                return this.RedirectToAction("Index");
            }

            var categories = this.personalCategoriesService.GetByUser(this.UserProfile.Id);
            this.ViewBag.CategoryId = new SelectList(categories, "Id", "Name", personalFeedInputModel.CategoryId);
            //this.ViewBag.FeedId = new SelectList(this.db.Feeds, "Id", "Url", personalFeedViewModel.FeedId);
            return this.View(personalFeedInputModel);
        }

        // GET: PersonalFeeds/Edit/5
        public ActionResult Edit(long? id)
        {
            var personalFeed = this.personalFeedsRepository.GetById(id);
            if (personalFeed == null)
            {
                return this.HttpNotFound();
            }

            var categories = this.personalCategoriesService.GetByUser(this.UserProfile.Id);
            this.ViewBag.CategoryId = new SelectList(categories, "Id", "Name", personalFeed.CategoryId);
            //this.ViewBag.FeedId = new SelectList(this.db.Feeds, "Id", "Url", personalFeed.FeedId);

            var personalFeedInputModel = Mapper.Map<PersonalFeedInputModel>(personalFeed);

            return this.View(personalFeedInputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PersonalFeedInputModel personalFeedInputModel)
        {
            if (this.ModelState.IsValid)
            {
                using (var transaction = new TransactionScope())
                {
                    if (!this.feedsService.ExistsByUrl(personalFeedInputModel.Url))
                    {
                        this.feedsRepository.Add(new Feed() { Url = personalFeedInputModel.Url });
                    }
                }

                var feed = this.feedsService.GetByUrl(personalFeedInputModel.Url);

                var personalFeed = Mapper.Map<PersonalFeed>(personalFeedInputModel);
                personalFeed.FeedId = feed.Id;

                this.personalFeedsRepository.Update(personalFeed);
                this.feedsRepository.SaveChanges();

                return this.RedirectToAction("Index");
            }

            var categories = this.personalCategoriesService.GetByUser(this.UserProfile.Id);
            this.ViewBag.CategoryId = new SelectList(categories, "Id", "Name", personalFeedInputModel.CategoryId);
            
            return this.View(personalFeedInputModel);
        }

        // GET: PersonalFeeds/Delete/5
        public ActionResult Delete(long? id)
        {
            var personalFeed = this.personalFeedsRepository.GetById(id);
            if (personalFeed == null)
            {
                return this.HttpNotFound();
            }

            var personalFeedViewModel = Mapper.Map<PersonalFeedViewModel>(personalFeed);
            return this.View(personalFeedViewModel);
        }

        // POST: PersonalFeeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var personalFeed = this.personalFeedsRepository.GetById(id);
            if (personalFeed == null)
            {
                return this.HttpNotFound();
            }

            this.personalFeedsRepository.Delete(id);
            this.personalFeedsRepository.SaveChanges();

            //this.db.PersonalFeeds.Remove(personalFeed);
            //this.db.SaveChanges();

            return this.RedirectToAction("Index");
        }
    }
}

RssFeed.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RSS Feed - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="logo">
                    <h1>@Html.ActionLink("Rss Feed", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</h1>
                </div>
            </div>
            <div id="header-nav" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Feeds", "Index", "PersonalFeeds")</li>
                    }
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li class="dropdown">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @*<nav id="header-nav">
            <div class="toggle-nav toggle-holder">
                <ul class="nav-list horizontal-list">
                    <li class="nav-item dropdown-item">
                        <a href="javascript:;" class="nav-link header-dropdown-link" data-toggle="dropdown">
                            <span class="cell">Rss Feed</span>
                        </a>
                        <div class="custom-dropdown">
                            <div class="container container-holder">
                                <ul class="dropdown-list row">
                                    <li class="col-md-3 col-sm-4">
                                        <a href="/about" class="nav-link">Aaaa</a>
                                    </li>
                                    <li class="col-md-3 col-sm-4">
                                        <a href="/curriculum" class="nav-link">Bb</a>
                                    </li>
                                    <li class="col-md-3 col-sm-4">
                                        <a href="/plans" class="nav-link">Cc</a>
                                    </li>
                                    <li class="col-md-3 col-sm-4">
                                        <a href="/diplomas-and-certificates" class="nav-link">Dd</a>
                                    </li>
                                    <li class="col-md-3 col-sm-4">
                                        <a href="/trainers" class="nav-link">Ee</a>
                                    </li>
                                    <li class="col-md-3 col-sm-4">
                                        <a href="/faq" class="nav-link">Ff</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rss Feed</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>